#!/usr/bin/env bash

echo 'starting'

for file in ./www/posts/**/*.md ; do
    echo "File: ${file}"
    if [[ "${file}" =~ ^(./www/posts/[0-9]{4}/)[0-9]{4}-[0-9]{2}-[0-9]{2}-(.*\.md) ]] ; then
        dest="${BASH_REMATCH[1]}${BASH_REMATCH[2]}"
        echo "  Dest: ${dest}"
        mv -v "${file}" "${dest}"
    fi
done