site_name: Nicolas Ventura
site_description: About Me
site_author: Nicolas Ventura
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-1
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  logo: icon.svg
  favicon: icon.svg
plugins:
  - search
  - blog
  - tags:
      tags_file: blog/tags.md
markdown_extensions:
  - attr_list
extra:
  social:
    - icon: material/web
      link: https://nicolasventura.com/
    - icon: material/email
      link: mailto:www@nicolasventura.com
      name: Send Email
    - icon: material/linkedin
      link: https://www.linkedin.com/in/nfv/
    - icon: material/book-open-page-variant
      link: https://nicfv.com/blog/
      name: Blog
    - icon: material/instagram
      link: https://www.instagram.com/nicfvcom/
    - icon: material/github
      link: https://github.com/nicfv
    - icon: material/stack-overflow
      link: https://stackoverflow.com/users/15317094/nfv
    - icon: material/microsoft-visual-studio
      link: https://marketplace.visualstudio.com/publishers/ventura
    - icon: material/npm
      link: https://www.npmjs.com/~nfv
    - icon: material/language-python
      link: https://pypi.org/user/nfv/
    - icon: simple/strava
      link: https://www.strava.com/athletes/nicfv
    - icon: material/format-letter-matches
      link: https://wordle.nicfv.com/
    - icon: material/hexagon
      link: https://hexles.com/
    - icon: material/chess-pawn
      link: https://www.chess.com/member/nicfv
  generator: false
copyright: Copyright &copy; 2023 Nicolas Ventura
