site_name: Nicolas Ventura
site_description: Portfolio
site_author: Nicolas Ventura
theme:
  name: material
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-1
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-3
        name: Switch to light mode
  favicon: icon.svg
plugins: []
extra:
  social:
    - icon: material/web
      link: https://nicolasventura.com/
    - icon: material/email
      link: mailto:nicolas@ventura.cx
  generator: false