site_name: Nicolas Ventura
site_description: About Me
site_author: Nicolas Ventura
strict: true
theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - navigation.tabs
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-2
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-1
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-3
        name: Switch to system preference
  logo: icon.png
  favicon: icon.png
plugins:
  - search
  - blog:
      blog_toc: true
  - tags:
      tags_file: blog/tags.md
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      auto_title: true
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - attr_list
extra_css:
  - extra.css
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: G-9J3K4KQP9R
  consent:
    title: Cookie consent
    description: This website uses cookies, including those from Google Analytics, to enhance your browsing experience and analyze site usage. By continuing to use this site, you consent to the use of cookies. Google Analytics employs cookies to assess website activity and provide insights for website optimization. The information generated, including your IP address, is transmitted to and stored by Google. You can opt-out by disabling cookies or using Google's opt-out service. You have the ability to control and delete cookies through your browser settings. Any changes to this notice will be posted on this page. If you have questions, please email me using the contact link at the bottom of this page. Thank you for your understanding and cooperation.
  social:
    - icon: material/web
      link: https://nicolasventura.com/
    - icon: material/email
      link: mailto:www@nicolasventura.com
      name: Send Email
    - icon: material/linkedin
      link: https://www.linkedin.com/in/nfv/
    - icon: material/youtube
      link: https://www.youtube.com/@n1cfv
    - icon: material/instagram
      link: https://www.instagram.com/n1cfv/
    - icon: material/github
      link: https://github.com/nicfv
    - icon: material/stack-overflow
      link: https://stackoverflow.com/users/15317094/nfv
    - icon: material/microsoft-visual-studio
      link: https://marketplace.visualstudio.com/publishers/ventura
    - icon: material/npm
      link: https://www.npmjs.com/~nicfv
    - icon: material/language-python
      link: https://pypi.org/user/nicfv/
    - icon: simple/strava
      link: https://www.strava.com/athletes/nicfv
    - icon: material/hexagon
      link: https://hexles.com/
    - icon: simple/duolingo
      link: https://www.duolingo.com/profile/nicfv
    - icon: material/chess-pawn
      link: https://www.chess.com/member/nicfv
  generator: false
copyright: Copyright &copy; 2024 Nicolas Ventura
